version: 2

jobs:
  build:
    branches:
      only:
        - master
    working_directory: ~/bluespan.gg
    docker:
      - image: python:3.8.0
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3.8 -m venv env
            env/bin/pip install -r requirements.txt
      - run:
          name: render rst
          command: |
            env/bin/python build.py
      - add_ssh_keys:
          fingerprints:
            - "af:fe:e4:34:8a:1a:7d:e4:78:24:0e:fe:fa:ab:39:3b"
      - run:
          name: deploy to bluespan.gg
          command: |
            apt update
            apt install -y rsync

            cat << EOF >> ~/.ssh/known_hosts
            direct.bluespan.gg,2001:19f0:6401:56d:5400:2ff:fe66:c84a,149.28.246.77 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBBMQcW5qmyq2ak4aRYHM5PuhhqEooaAJndaZ29XyQmHSeYP8wzrvel6i1ybyN8R/QxfeOcT3PvA2OIFTjYxuT10=
            EOF

            rsync \
              --rsync-path=/usr/bin/openrsync \
              --delete -arv \
              ./build/ \
              root@direct.bluespan.gg:/var/www/htdocs/bluespan.gg
