version: 2

jobs:
  build:
    working_directory: ~/bluespan.gg
    docker:
      - image: python:3.8.0
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3.8 -m venv env
            env/bin/pip install -r requirements.txt
      - run:
          name: render rst
          command: |
            env/bin/python build.py
      - add_ssh_keys:
          fingerprints:
            - "af:fe:e4:34:8a:1a:7d:e4:78:24:0e:fe:fa:ab:39:3b"
      - run:
          name: deploy to bluespan.gg
          command: |
            apt update
            apt install -y rsync

            rsync \
              --rsync-path=/usr/bin/openrsync \
              --delete -arv \
              ./build/ \
              root@direct.bluespan.gg:/var/www/htdocs/bluespan.gg
