version: 2

jobs:
  build:
    working_directory: ~/build
    docker:
      - image: python:3.8.0
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3.8 -m venv env
            env/bin/pip install -r requirements.txt
      - run:
          name: render rst
          command: |
            env/bin/python build.py
