version: 2

jobs:
  build:
    branches:
      only:
        - master
    working_directory: ~/bluespan.gg
    docker:
      - image: python:3.8.0
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3.8 -m venv env
            env/bin/pip install -r requirements.txt
      - run:
          name: render rst
          command: |
            env/bin/python build.py
      - add_ssh_keys:
          fingerprints:
            - "e6:4f:df:2e:5d:3a:d3:e3:61:a7:84:8f:c9:dd:66:dd"
      - run:
          name: deploy to bluespan.gg
          command: |
            apt update
            apt install -y rsync

            cat << EOF >> ~/.ssh/known_hosts
            ed5rpzdi.lax.bluespan.gg,2001:19f0:6001:509f:5400:2ff:fe6b:19ff,45.77.68.171 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPTWYlTdGuLMakaC14VBZ6dYAVB/iGT6VPt8qvGrQGuLWIvAZyQO+nRBlkslmHQiAZFr7/V9P/q2C+0pKdYtHMs=
            EOF

            rsync \
              --delete -arv \
              ./build/ \
              deploy@ed5rpzdi.lax.bluespan.gg:/home/deploy/bluespan.gg

            ssh deploy@ed5rpzdi.lax.bluespan.gg doas /sbin/rc-service giveaway restart
